name: Upload data to production database on release

on:
  release:
    types: [released]

jobs:
  publish:
    uses: geological-survey-of-queensland/vocabularies/.github/workflows/upload_to_database.yml@master
    with:
      environment: production
      request_timeout: 300
    secrets:
      prez_url: ${{ secrets.PREZ_URL }}
      database_url: ${{ secrets.FUSEKI_DATASET_URL }}
      database_username: ${{ secrets.FUSEKI_USERNAME }}
      database_password: ${{ secrets.FUSEKI_PASSWORD }}
